showTodos:
  path: /
  controller: App\Controller\TodosController::showTodos

completeTodo:
  path: /complete
  controller: App\Controller\TodosController::toggleTodoCompleteness
  defaults:
    status: 1

uncompleteTodo:
  path: /uncomplete
  controller: App\Controller\TodosController::toggleTodoCompleteness
  defaults:
    status: 0
